[package]
name = "volcano-sfu"
version = "0.4.0"
edition = "2024"
authors = ["Ian Parra <ianparra200@gmail.com>"]
description = "Selective Forwarding Unit (SFU) for WebRTC signaling apps"
repository = "https://github.com/MilcaoStudio/volcano"
readme = "README.md"
license = "MIT"
keywords = ["webrtc", "sfu", "rtc", "subscriber", "publisher", "datachannel"]
categories = ["network-programming", "async"]

[dependencies]
# Async
async-trait = "0.1.83"
tokio = { version = "1.37.0", features = ["full"] }

anyhow = "1.0.82"
byteorder = "1.5.0"
bytes = "1.6.0"
dashmap = "6.1.0"
log = "0.4.21"
postage = "0.5.0"
rand = "0.8.5"
regex = "1.10.4"
ulid = "1.1.2"

# Error
thiserror = "1.0.58"

# Serde
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

# WebRTC
webrtc = "0.13.0"

# Configuration parsers
toml = { version = "0.9.2", optional = true }

[features]
default = ["toml"]
turn = []
toml = ["dep:toml"]
