use std::future::Future;
use std::sync::atomic::{AtomicBool, Ordering};
use std::{pin::Pin, sync::Arc};

use dashmap::DashMap;
use tokio::sync::Mutex;
use tokio::sync::broadcast::Sender;
use tokio::sync::{broadcast, mpsc};
use tokio::time::{Duration, sleep};
use webrtc::peer_connection::peer_connection_state::RTCPeerConnectionState;
use webrtc::rtcp::header::PacketType;
use webrtc::rtcp::packet::Packet as RtcpPacket;
use webrtc::rtcp::sender_report::SenderReport;
use webrtc::rtp_transceiver::rtp_codec::{RTCRtpCodecCapability, RTPCodecType};
use webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver;
use webrtc::rtp_transceiver::rtp_transceiver_direction::RTCRtpTransceiverDirection;
use webrtc::rtp_transceiver::{RTCPFeedback, RTCRtpTransceiverInit};
use webrtc::track::track_remote::TrackRemote;

use super::downtrack::{DownTrack, DownTrackInternal};
use super::error::Result;
use super::receiver::{Receiver, RtcpDataReceiver, RtcpDataSender, WebRTCReceiver};
use crate::buffer::Options as BufferOptions;
use crate::rtc::peer::{self, Subscriber};
use crate::rtc::room::{Room, RoomEvent};
use crate::track::audio_observer::AudioObserver;
use crate::{buffer::AtomicFactory, buffer::BufferIO, rtc::config::RouterConfig};

pub type RtcpWriterFn = Box<
    dyn (FnMut(
            Vec<Box<dyn RtcpPacket + Send + Sync>>,
        ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'static>>)
        + Send
        + Sync,
>;
pub type OnAddReciverTrackFn = Box<
    dyn (FnMut(
            Arc<dyn Receiver + Send + Sync>,
        ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'static>>)
        + Send
        + Sync,
>;
pub type OnDelReciverTrackFn = Box<
    dyn (FnMut(
            Arc<dyn Receiver + Send + Sync>,
        ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'static>>)
        + Send
        + Sync,
>;
pub struct LocalRouter {
    closed: AtomicBool,
    id: String,
    pub audio_observer: Arc<Mutex<AudioObserver>>,
    //twcc: Arc<Mutex<Option<Responder>>>,
    rtcp_sender_channel: Arc<RtcpDataSender>,
    rtcp_receiver_channel: Arc<Mutex<RtcpDataReceiver>>,
    stop_sender_channel: Arc<Sender<()>>,
    config: RouterConfig,
    receivers: Arc<Mutex<DashMap<String, Arc<WebRTCReceiver>>>>,
    buffer_factory: AtomicFactory,
    rtcp_writer_handler: Arc<Mutex<Option<RtcpWriterFn>>>,
    room: Arc<Room>,
    on_add_receiver_track_handler: Arc<Mutex<Option<OnAddReciverTrackFn>>>,
    on_del_receiver_track_handler: Arc<Mutex<Option<OnDelReciverTrackFn>>>,
}

impl LocalRouter {
    /// Creates a Router instance.
    /// # Arguments
    /// - `id`: Unique identifier of this router.
    /// - `room`: [Room] instance.
    /// - `config`: [RouterConfig] instance.
    pub fn new(id: String, room: Arc<Room>, config: RouterConfig) -> Self {
        let (s, r) = mpsc::channel(1024);
        let (sender, _) = broadcast::channel(1);
        let audio_threshold = config.audio_level_threshold;
        let audio_interval = config.audio_level_interval;
        let audio_filter = config.audio_level_filter;
        let audio_observer = AudioObserver::new(audio_threshold, audio_interval, audio_filter);
        Self {
            closed: AtomicBool::default(),
            id,
            //twcc: Arc::new(Mutex::new(None)),
            //stats: Arc::new(Mutex::new(HashMap::new())),
            audio_observer: Arc::new(Mutex::new(audio_observer)),
            rtcp_sender_channel: Arc::new(s),
            rtcp_receiver_channel: Arc::new(Mutex::new(r)),
            stop_sender_channel: Arc::new(sender),
            config,
            receivers: Arc::new(Mutex::new(DashMap::new())),
            room,
            buffer_factory: AtomicFactory::default(),
            rtcp_writer_handler: Arc::new(Mutex::new(None)),
            on_add_receiver_track_handler: Arc::new(Mutex::new(None)),
            on_del_receiver_track_handler: Arc::new(Mutex::new(None)),
        }
    }

    /// Registers a function to be called when a new receiver is added.
    pub async fn register_on_add_receiver_track(&self, f: OnAddReciverTrackFn) {
        let mut handler = self.on_add_receiver_track_handler.lock().await;
        *handler = Some(f);
    }

    /// Registers a function to be called when a receiver is removed.
    pub async fn register_on_del_receiver_track(&self, f: OnDelReciverTrackFn) {
        let mut handler = self.on_del_receiver_track_handler.lock().await;
        *handler = Some(f);
    }

    /// Unique identifier of this router.
    pub fn id(&self) -> String {
        self.id.clone()
    }

    /// Gets the [DownTrack] from the subscriber if it exists.
    /// Otherwise, creates a new [DownTrack], which is added to the [Subscriber] and the [Receiver].
    ///
    /// The [DownTrack] is generated by subscriber's peer connection.
    ///
    /// # Returns
    /// - `Ok(Some(Arc<DownTrack>))` if the track was added.
    /// - `Err(Error)` if the track could not be added (e.g. the receiver is closed).
    pub async fn add_down_track(
        &self,
        subscriber: Arc<Subscriber>,
        receiver: Arc<WebRTCReceiver>,
    ) -> Result<Arc<DownTrack>> {
        let downtracks = subscriber.get_tracks(&receiver.stream_id()).await;
        // Checks for available tracks
        if let Some(downtracks_data) = downtracks {
            for dt in downtracks_data {
                // Returns track if exists
                if dt.id() == receiver.track_id() {
                    info!("LocalRouter::add_down_track Downtrack exists");
                    return Ok(dt);
                }
            }
        }

        let codec = receiver.codec();
        subscriber
            .m
            .lock()
            .await
            .register_codec(codec.clone(), receiver.kind())?;
        let codec_capability = RTCRtpCodecCapability {
            mime_type: codec.capability.mime_type,
            clock_rate: codec.capability.clock_rate,
            channels: codec.capability.channels,
            sdp_fmtp_line: codec.capability.sdp_fmtp_line,
            rtcp_feedback: vec![
                RTCPFeedback {
                    typ: String::from("goog-remb"),
                    parameter: String::from(""),
                },
                RTCPFeedback {
                    typ: String::from("nack"),
                    parameter: String::from(""),
                },
                RTCPFeedback {
                    typ: String::from("nack"),
                    parameter: String::from("pli"),
                },
            ],
        };

        // New local down track
        let down_track_local = Arc::new(DownTrackInternal::new(
            codec_capability,
            receiver.clone(),
            self.config.max_packet_track,
        ));
        let transceiver = subscriber
            .pc
            .add_transceiver_from_track(
                down_track_local.clone(),
                Some(RTCRtpTransceiverInit {
                    direction: RTCRtpTransceiverDirection::Sendonly,
                    send_encodings: Vec::new(),
                }),
            )
            .await?;
        info!(
            "[Subscriber {}] {} transceivers",
            subscriber.id,
            subscriber.pc.get_transceivers().await.len()
        );
        // New local track
        let mut down_track = DownTrack::new_track_local(subscriber.id.clone(), down_track_local);
        down_track.set_transceiver(transceiver.clone());
        let down_track_arc = Arc::new(down_track);

        let s_out = subscriber.clone();
        let r_out = receiver.clone();
        let down_track_out = down_track_arc.clone();
        down_track_arc
            .register_on_close(Box::new(move || {
                let s_in = s_out.clone();
                let r_in = r_out.clone();
                let transceiver_in = transceiver.clone();
                let down_track_in = down_track_out.clone();
                Box::pin(async move {
                    if s_in.pc.connection_state() != RTCPeerConnectionState::Closed {
                        // Remove track from subscriber peer connection
                        match s_in.pc.remove_track(&transceiver_in.sender().await).await {
                            Ok(_) => {
                                info!("Remove DownTrack for {}", &r_in.stream_id());
                                s_in.remove_down_track(&r_in.stream_id(), &down_track_in)
                                    .await;

                                // Force negotiation
                                if let Err(err) = s_in.negotiate(None).await {
                                    error!("Negotiation for track removed failed:{} ", err);
                                }
                            }
                            Err(err) => {
                                error!("remove_down_track err: {}", err);
                            }
                        }
                    }
                })
            }))
            .await;

        let s_out_1 = subscriber.clone();
        let r_out_1 = receiver.clone();
        down_track_arc
            .register_on_bind(Box::new(move || {
                let s_in = s_out_1.clone();
                let r_in = r_out_1.clone();

                Box::pin(async move {
                    tokio::spawn(async move {
                        s_in.send_stream_down_track_reports(&r_in.stream_id()).await;
                    });
                })
            }))
            .await;

        info!(
            "[Router {}] Local track {} created",
            self.id,
            down_track_arc.id()
        );

        subscriber
            .add_down_track(receiver.stream_id(), down_track_arc.clone())
            .await;

        receiver
            .add_down_track(
                down_track_arc.clone(),
                self.config.simulcast.best_quality_first,
            )
            .await
            .map(|_| down_track_arc)
    }

    /// Copies the tracks from `receiver` to `subscriber`. Then, copies all the tracks from the router's receivers to `subscriber`.
    ///
    /// This operation is skipped if [Subscriber::no_auto_subscribe] is true.
    /// # Arguments
    /// - `subscriber`: [Subscriber] to add the tracks to.
    /// - `receiver`: [Receiver] to copy the tracks from.
    ///
    /// # Returns
    /// - `Ok(bool)` if the operation was successful (or skipped). New negotiation is suggested when returns `true`.
    /// - `Err(Error)` if the operation failed (e.g. subscriber's negotiation failed).
    pub async fn add_down_tracks(
        &self,
        subscriber: Arc<Subscriber>,
        receiver: Option<Arc<WebRTCReceiver>>,
    ) -> peer::error::Result<bool> {
        let mut should_negotiate = false;
        if subscriber.no_auto_subscribe {
            info!(
                "Router[{}] add_down_tracks Subscriber skips [no_auto_subscribe]",
                self.id
            );
            return Ok(should_negotiate);
        }

        if let Some(receiver) = receiver {
            info!(
                "[Router {}] add_down_tracks Subscriber {} adds a downtrack from receiver",
                self.id, subscriber.id
            );
            if let Err(err) = self.add_down_track(subscriber.clone(), receiver).await {
                error!("add_down_track err: {}", err);
            };
            should_negotiate = true;
        }

        let recs = self
            .receivers
            .lock()
            .await
            .iter()
            .map(|r| r.clone())
            .collect::<Vec<_>>();

        if !recs.is_empty() {
            info!(
                "[Router {}] Subscriber {} adds downtracks from stored receivers",
                self.id, subscriber.id
            );
            for val in &recs {
                if let Err(err) = self.add_down_track(subscriber.clone(), val.clone()).await {
                    error!("add_down_track err: {}", err);
                };
            }
            should_negotiate = true;
        }

        Ok(should_negotiate)
    }

    /// Adds a new [Receiver] to this router if it doesn't exist, otherwise, returns the existing receiver.
    ///
    /// # Audio level detection
    /// If `track`'s kind is [RTPCodecType::Audio], [Self::audio_observer] will observe audio levels of the track.
    ///
    /// # RTP listener
    /// Every RTP packet received by `track` will be forwarded to a buffer.
    ///
    /// # Arguments
    /// - `receiver`: [RTCRtpReceiver] used to create the [Receiver].
    /// - `track`: [TrackRemote] where RTP packets will be read from.
    ///
    /// # Returns
    /// (receiver, published)
    /// - `receiver`: [Receiver] that was created or fetched.
    /// - `published`: Whether the receiver was created or fetched.
    pub async fn add_receiver(
        self: &Arc<Self>,
        rtp_receiver: Arc<RTCRtpReceiver>,
        track: Arc<TrackRemote>,
        //track_id: String,
        //stream_id: String,
    ) -> (Arc<WebRTCReceiver>, bool) {
        let track_id = track.id();
        let stream_id = track.stream_id();
        let mut published = false;
        let buffer = self.buffer_factory.get_or_new_buffer(track.ssrc()).await;
        let sender = self.rtcp_sender_channel.clone();
        buffer
            .register_on_feedback(Box::new(
                move |packets: Vec<Box<dyn RtcpPacket + Send + Sync>>| {
                    let sender_in = Arc::clone(&sender);
                    Box::pin(async move {
                        if let Err(err) = sender_in.send(packets).await {
                            error!("send err: {}", err);
                        }
                    })
                },
            ))
            .await;

        match track.kind() {
            RTPCodecType::Audio => {
                let audio_observer = self.audio_observer.clone();
                let stream_id_out = stream_id.clone();
                buffer
                    .register_on_audio_level(Box::new(move |voice, level| {
                        let audio_observer_in = audio_observer.clone();
                        let stream_id_in = stream_id_out.clone();
                        Box::pin(async move {
                            if !voice {
                                debug!("Skip observation");
                                return;
                            }
                            audio_observer_in
                                .lock()
                                .await
                                .observe(&stream_id_in, level)
                                .await;
                        })
                    }))
                    .await;
                debug!(
                    "[Router {}] add stream {} to audio observer",
                    self.id, stream_id
                );
                self.audio_observer.lock().await.add_stream(stream_id).await;
            }
            RTPCodecType::Video => {
                // TODO: implement video rotation detection
            }
            _ => {}
        }

        // TODO: implement twcc
        // TODO: implement stats

        let rtcp_reader = self
            .buffer_factory
            .get_or_new_rtcp_buffer(track.ssrc())
            .await;
        //let stats_out = Arc::clone(&self.stats);
        let buffer_out = Arc::clone(&buffer);
        let with_status = self.config.with_stats;
        rtcp_reader
            .set_on_packets(Box::new(move |pkts| {
                let buffer_in = Arc::clone(&buffer_out);
                Box::pin(async move {
                    for pkt in pkts {
                        match pkt.header().packet_type {
                            PacketType::SourceDescription => {
                                // TODO: send stats
                                info!("Packet SourceDescription received");
                            }
                            PacketType::SenderReport => {
                                info!("Packet SenderReport");
                                if let Some(sender_report) =
                                    pkt.as_any().downcast_ref::<SenderReport>()
                                {
                                    buffer_in
                                        .set_sender_report_data(
                                            sender_report.rtp_time,
                                            sender_report.ntp_time,
                                        )
                                        .await;
                                    if with_status {
                                        // TODO: update stats
                                    }
                                };
                            }
                            packet_type => {
                                debug!("Unhandled packet type {}", packet_type);
                            }
                        }
                    }
                })
            }))
            .await;

        let receivers = self.receivers.lock().await;
        let arc_receiver;
        match receivers.get(&track_id) {
            Some(r) => arc_receiver = r.clone(),
            None => {
                let rtc_rv = self
                    .create_receiver(rtp_receiver.clone(), track.clone())
                    .await;
                arc_receiver = Arc::new(rtc_rv);
                receivers.insert(track_id, arc_receiver.clone());
                published = true;
                info!("Track {} published", track.id());

                info!(
                    "[Publisher {}] Reading RTCP packets from {}",
                    self.id,
                    track.id()
                );
                let rtp_rv1 = rtp_receiver.clone();
                tokio::spawn(async move {
                    // Use mtu size (1460)
                    while let Ok((pkts, _)) = rtp_rv1.read_rtcp().await {
                        rtcp_reader.send_packets(pkts).await;
                    }
                });

                if let Some(f) = &mut *self.on_add_receiver_track_handler.lock().await {
                    let _ = f(arc_receiver.clone()).await;
                }
            }
        }
        let layer = arc_receiver
            .add_up_track(
                track.clone(),
                buffer.clone(),
                self.config.simulcast.best_quality_first,
            )
            .await;

        if let Some(layer_val) = layer {
            let receiver_clone = arc_receiver.clone();
            tokio::spawn(async move { receiver_clone.write_rtp(layer_val).await });
        }

        buffer
            .bind(
                rtp_receiver.get_parameters().await,
                BufferOptions {
                    max_bitrate: self.config.max_bandwidth,
                },
            )
            .await;
        let buffer_clone = buffer.clone();

        info!(
            "[Publisher {}] Reading RTP packets from {}",
            self.id,
            track.id()
        );
        tokio::spawn(async move {
            // Use mtu size (1460)
            while let Ok((pkt, _)) = track.read_rtp().await {
                buffer_clone.write(pkt).await;
            }
        });
        (arc_receiver, published)
    }

    async fn create_receiver(
        &self,
        rtp_receiver: Arc<RTCRtpReceiver>,
        track: Arc<TrackRemote>,
    ) -> WebRTCReceiver {
        let mut rv = WebRTCReceiver::new(rtp_receiver.clone(), track.clone(), self.id.clone());
        rv.set_rtcp_channel(self.rtcp_sender_channel.clone());
        let recv_kind = rv.kind();
        let stream_id = track.stream_id();
        let audio_observer = self.audio_observer.clone();
        rv.register_on_close(Box::new(move || {
            let stream_id_in = stream_id.clone();
            let observer_in = audio_observer.clone();
            Box::pin(async move {
                if recv_kind == RTPCodecType::Audio {
                    observer_in.lock().await.remove_stream(&stream_id_in).await;
                }
            })
        }))
        .await;
        rv
    }

    /// Starts a task that observes audio levels of the tracks in this router.
    ///
    /// Fires [RoomEvent::VoiceActivity] when audio activity from streams changes.
    ///
    /// Stops when `stop` signal is received.
    pub async fn start_audio_observer_task(&self) {
        let mut stop_receiver = self.stop_sender_channel.subscribe();
        let id_out = self.id.clone();
        let observer = self.audio_observer.clone();
        let interval_ms = observer.lock().await.interval as u64;
        let interval = Duration::from_millis(interval_ms);
        let room_out = self.room.clone();
        tokio::spawn(async move {
            loop {
                tokio::select! {
                    _ = sleep(interval) => {
                        let is_empty = {
                            observer.lock().await.is_empty().await
                        };

                        if is_empty {
                            continue;
                        }

                        let streams = {
                            observer.lock().await.calc().await
                        };

                        if let Some(streams) = streams {
                            info!("Streams {:?}", streams);
                            room_out.send_message(RoomEvent::VoiceActivity { room_id: room_out.id.clone(), stream_ids: streams }).await;
                        }
                    }
                    _ = stop_receiver.recv() => {
                        info!("[Router {}] Stopping audio observer task", id_out);
                        break;
                    }
                }
            }
        });
    }

    /// Sets the function to be called when an RTCP packet is received.
    pub async fn set_rtcp_writer(&self, writer: RtcpWriterFn) {
        let mut handler = self.rtcp_writer_handler.lock().await;
        *handler = Some(writer);
    }

    /// Forwards RTCP packets to the RTCP writer.
    pub async fn send_rtcp(&self) {
        let mut stop = self.stop_sender_channel.subscribe();
        let mut rtcp_receiver = self.rtcp_receiver_channel.lock().await;
        loop {
            //let mut rtcp_receiver = self.rtcp_receiver_channel.lock().await;
            tokio::select! {
              data = rtcp_receiver.recv() => {
                 if let Some(val) = data{
                    if let Some(f) = &mut *self.rtcp_writer_handler.lock().await {
                        let _ = f(val).await;
                    }
                }
              }
              _data = stop.recv() => {
                info!("Stop receiver signal. Exiting loop");
                return ;
              }
            };
        }
    }

    /// Sends `stop` signal in this router, and safely shuts down all associated receivers.
    /// This function is idempotent: it ensures that cleanup logic runs only once.
    /// Subsequent calls have no effect and return immediately.
    pub async fn stop(&self) {
        if self.closed.swap(true, Ordering::SeqCst) {
            trace!("[Router {}] stop, router already closed.", self.id);
            return;
        }

        info!("[Router {}] Stopping receivers", self.id);
        for item in self.receivers.lock().await.iter() {
            let id = item.key();
            let receiver = item.value();

            info!("[Router {}] Closing receiver {}", self.id, id);
            receiver.close_tracks().await;
        }

        if let Err(err) = self.stop_sender_channel.send(()) {
            error!("stop err: {}", err);
        }
    }
}

impl Drop for LocalRouter {
    fn drop(&mut self) {
        if let Err(err) = self.stop_sender_channel.send(()) {
            error!("stop err: {}", err);
        }
    }
}
