use std::future::Future;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Weak;
use std::{pin::Pin, sync::Arc};

use dashmap::DashMap;
use tokio::sync::Mutex;
use tokio::sync::broadcast::Sender;
use tokio::sync::{broadcast, mpsc};
use tokio::time::{interval, sleep, Duration};
use webrtc::rtcp::goodbye::Goodbye;
use webrtc::rtcp::header::PacketType;
use webrtc::rtcp::packet::Packet as RtcpPacket;
use webrtc::rtcp::sender_report::SenderReport;
use webrtc::rtcp::source_description::SourceDescription;
use webrtc::rtp_transceiver::rtp_codec::{RTCRtpCodecCapability, RTPCodecType};
use webrtc::rtp_transceiver::rtp_receiver::RTCRtpReceiver;
use webrtc::rtp_transceiver::RTCPFeedback;
use webrtc::track::track_remote::TrackRemote;

use super::downtrack::DownTrack;
use super::error::Result;
use super::receiver::{Receiver, RtcpDataReceiver, RtcpDataSender, WebRTCReceiver};
use crate::packet::Options as PacketOptions;
use crate::peer::{self, Consumer};
use crate::session::config::RouterConfig;
use crate::session::room::{Room, RoomEvent};
use crate::track::audio_observer::AudioObserver;
use crate::track::error::Error;
use crate::{packet::AtomicFactory, packet::BufferIO};

pub type RtcpWriterFn = Box<
    dyn (FnMut(
            Vec<Box<dyn RtcpPacket + Send + Sync>>,
        ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'static>>)
        + Send
        + Sync,
>;
pub type OnAddReciverTrackFn = Box<
    dyn (FnMut(
            Arc<dyn Receiver + Send + Sync>,
        ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'static>>)
        + Send
        + Sync,
>;
pub type OnDelReciverTrackFn = Box<
    dyn (FnMut(
            Arc<dyn Receiver + Send + Sync>,
        ) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'static>>)
        + Send
        + Sync,
>;
pub struct LocalRouter {
    closed: AtomicBool,
    id: String,
    pub audio_observer: Arc<Mutex<AudioObserver>>,
    //twcc: Arc<Mutex<Option<Responder>>>,
    rtcp_sender_channel: Arc<RtcpDataSender>,
    rtcp_receiver_channel: Arc<Mutex<RtcpDataReceiver>>,
    stop_sender_channel: Arc<Sender<()>>,
    config: RouterConfig,
    receivers: Arc<DashMap<String, Arc<WebRTCReceiver>>>,
    pub buffer_factory: Arc<AtomicFactory>,
    rtcp_writer_handler: Arc<Mutex<Option<RtcpWriterFn>>>,
    room: Weak<Room>,
    on_add_receiver_track_handler: Arc<Mutex<Option<OnAddReciverTrackFn>>>,
    on_del_receiver_track_handler: Arc<Mutex<Option<OnDelReciverTrackFn>>>,
}

impl LocalRouter {
    /// Creates a Router instance.
    /// # Arguments
    /// - `id`: Unique identifier of this router.
    /// - `room`: [Room] instance.
    /// - `config`: [RouterConfig] instance.
    pub fn new(id: String, room: Weak<Room>, config: RouterConfig) -> Self {
        let (s, r) = mpsc::channel(1024);
        let (sender, _) = broadcast::channel(1);
        let audio_threshold = config.audio_level_threshold;
        let audio_interval = config.audio_level_interval;
        let audio_filter = config.audio_level_filter;
        let audio_observer = AudioObserver::new(audio_threshold, audio_interval, audio_filter);
        Self {
            closed: AtomicBool::default(),
            id,
            //twcc: Arc::new(Mutex::new(None)),
            //stats: Arc::new(Mutex::new(HashMap::new())),
            audio_observer: Arc::new(Mutex::new(audio_observer)),
            rtcp_sender_channel: Arc::new(s),
            rtcp_receiver_channel: Arc::new(Mutex::new(r)),
            stop_sender_channel: Arc::new(sender),
            config,
            receivers: Arc::default(),
            room,
            buffer_factory: Arc::default(),
            rtcp_writer_handler: Arc::new(Mutex::new(None)),
            on_add_receiver_track_handler: Arc::new(Mutex::new(None)),
            on_del_receiver_track_handler: Arc::new(Mutex::new(None)),
        }
    }

    /// Registers a function to be called when a new receiver is added.
    pub async fn register_on_add_receiver_track(&self, f: OnAddReciverTrackFn) {
        let mut handler = self.on_add_receiver_track_handler.lock().await;
        *handler = Some(f);
    }

    /// Registers a function to be called when a receiver is removed.
    pub async fn register_on_del_receiver_track(&self, f: OnDelReciverTrackFn) {
        let mut handler = self.on_del_receiver_track_handler.lock().await;
        *handler = Some(f);
    }

    /// Unique identifier of this router.
    pub fn id(&self) -> String {
        self.id.clone()
    }

    /// Gets the [DownTrack] from the subscriber if it exists.
    /// Otherwise, creates a new [DownTrack], which is added to the [Subscriber] and the [Receiver].
    ///
    /// The [DownTrack] is generated by subscriber's peer connection.
    ///
    /// # Returns
    /// - `Ok(Some(Arc<DownTrack>))` if the track was added.
    /// - `Err(Error)` if the track could not be added (e.g. the receiver is closed).
    pub async fn add_down_track(
        &self,
        consumer: Arc<dyn Consumer + Send + Sync>,
        receiver: Arc<WebRTCReceiver>,
    ) -> Result<Arc<DownTrack>> {
        let existing_dt = consumer.down_track_by_id(&receiver.track_id());
        // Checks for existing track
        if let Some(dt) = existing_dt {
            info!("LocalRouter::add_down_track Downtrack exists");
            return Ok(dt);
        }

        let codec = receiver.codec();
        let codec_capability = RTCRtpCodecCapability {
            mime_type: codec.capability.mime_type,
            clock_rate: codec.capability.clock_rate,
            channels: codec.capability.channels,
            sdp_fmtp_line: codec.capability.sdp_fmtp_line,
            rtcp_feedback: vec![
                RTCPFeedback {
                    typ: String::from("goog-remb"),
                    parameter: String::from(""),
                },
                RTCPFeedback {
                    typ: String::from("nack"),
                    parameter: String::from(""),
                },
                RTCPFeedback {
                    typ: String::from("nack"),
                    parameter: String::from("pli"),
                },
            ],
        };
        
        let down_track_arc = match consumer.new_local_track(codec_capability, &receiver, self.buffer_factory.clone()).await {
            Ok(dt) => dt,
            Err(peer::Error::ErrRTC(err)) => {
                return Err(err.into());
            }
            Err(err) => {
                error!("new local track error {err}");
                return Err(Error::ErrInvalidTrack);
            }
        };

        consumer.add_down_track(down_track_arc.clone());

        let layer = receiver.get_available_layer(self.config.simulcast.best_quality_first).await;

        //let s_out = consumer.clone();
        let r_out = receiver.clone();
        //let down_track_out = down_track_arc.clone();
        let track_id = down_track_arc.id().clone();
        down_track_arc
        .on_close(Box::new(move || {
            let track_id_in = track_id.clone();
            debug!("[Downtrack {}] Do on_close (layer {layer})", track_id_in);
            //let s_in = s_out.clone();
            let receiver_in = r_out.clone();
            //let down_track_in = down_track_out.clone();
            Box::pin(async move {
                if let Err(err) = receiver_in.delete_down_track(layer, &track_id_in).await {
                    warn!("delete_down_track failed: {err}");
                };
            })
        }))
        .await;
        let c_out = Arc::downgrade(&consumer);
        let dt_out = down_track_arc.clone();
        let factory = self.buffer_factory.clone();
        down_track_arc.on_bind(Box::new(move || {
            let consumer_in = c_out.clone();
            let dt_in = dt_out.clone();
            let chunks = dt_in.create_source_description_chunks();
            let packets: Vec<Box<dyn RtcpPacket + Send + Sync>> = vec![
                Box::new(SourceDescription { chunks: chunks.clone() }),
            ];
            let mut interval = interval(Duration::from_secs(5));
            //let factory_in = factory.clone();
            let rtcp_forwarder = factory.get_rtcp_buffer(dt_in.ssrc());
            Box::pin(async move {
                let Some(transceiver) = &*dt_in.transceiver.read().await else {
                    warn!("Expected transceiver for downtrack {}", dt_in.id());
                    return;
                };
                let sender = transceiver.sender().await;
                loop {
                    tokio::select! {
                        _ = interval.tick() => {
                            trace!("Write {} SDES chunks", packets.len());
                            match consumer_in.upgrade() {
                                Some(consumer) => {
                                    if let Err(err) = consumer.write_rtcp(packets.clone()).await {
                                        warn!("Write failed: {err}. Exit loop.");
                                        break;
                                    };
                                },
                                _ => {
                                    break;
                                },
                            }
                        },
                        result = sender.read_rtcp() => {
                            match result {
                                Ok((pkts, _)) => {
                                    match &rtcp_forwarder {
                                        Some(rtcp) => rtcp.send_packets(pkts).await,
                                        _ => {
                                            debug!("No rtcp forwarder for {}", dt_in.ssrc());
                                        },
                                    };
                                },
                                Err(err) => {
                                    debug!("dt read rtcp error: {err}");
                                    break;
                                },
                            }
                        },
                        // TODO: close channel
                    }
                }
            })
        })).await;
        
        // Task: Forward RTP
        let receiver_1 = receiver.clone();
        tokio::spawn(async move {
            info!("[Receiver {}] Looping for layer {layer} started.", receiver_1.track_id());
            loop {
                if let Err(err) = receiver_1.forward_rtp_packet(layer).await {
                    info!("Forward RTP closed: {err}");
                    break;
                };
            }
        });

        info!(
            "[Router {}] Local track {} created",
            self.id,
            down_track_arc.id()
        );

        // subscriber.add_down_track moved to subscriber.create_down_track

        receiver
            .add_down_track(
                down_track_arc.clone(),
                layer,
            )
            .await
            .map(|_| down_track_arc)
    }

    /// Copies the tracks from `receiver` to `subscriber`. Then, copies all the tracks from the router's receivers to `subscriber`.
    ///
    /// This operation is skipped if [Subscriber::no_auto_subscribe] is true.
    /// # Arguments
    /// - `subscriber`: [Subscriber] to add the tracks to.
    /// - `receiver`: [Receiver] to copy the tracks from.
    ///
    /// # Returns
    /// - `Ok(bool)` if the operation was successful (or skipped). New negotiation is suggested when returns `true`.
    /// - `Err(Error)` if the operation failed (e.g. subscriber's negotiation failed).
    pub async fn add_down_tracks(
        &self,
        subscriber: Arc<dyn Consumer + Send + Sync>,
        receiver: Option<Arc<WebRTCReceiver>>,
    ) -> peer::Result<bool> {
        let mut should_negotiate = false;
        let consumer_id = subscriber.id();
        if let Some(receiver) = receiver {
            info!(
                "[Router {}] add_down_tracks Subscriber {} adds a downtrack from receiver",
                self.id, consumer_id
            );
            if let Err(err) = self.add_down_track(subscriber.clone(), receiver).await {
                error!("add_down_track err: {}", err);
            };
            should_negotiate = true;
        }
        
        let recs = &self.receivers;
        if !recs.is_empty() {
            info!(
                "[Router {}] Subscriber {} adds downtracks from stored receivers",
                self.id, consumer_id
            );
            for val in recs.iter() {
                if let Err(err) = self.add_down_track(subscriber.clone(), val.clone()).await {
                    error!("add_down_track err: {}", err);
                };
            }
            should_negotiate = true;
        }

        Ok(should_negotiate)
    }

    /// Adds a new [Receiver] to this router if it doesn't exist, otherwise, returns the existing receiver.
    ///
    /// # Audio level detection
    /// If track's kind is [RTPCodecType::Audio], [Self::audio_observer] will observe audio levels of the track.
    ///
    /// # RTP listener
    /// Every RTP packet received by `track` will be forwarded to a buffer.
    ///
    /// # Arguments
    /// - `receiver`: [RTCRtpReceiver] used to create the [Receiver].
    /// - `track`: [TrackRemote] where RTP packets will be read from.
    ///
    /// # Returns
    /// (receiver, published)
    /// - `receiver`: [Receiver] that was created or fetched.
    /// - `published`: Whether the receiver was created or fetched.
    pub async fn add_uptrack(
        &self,
        rtp_receiver: Arc<RTCRtpReceiver>,
        track: Arc<TrackRemote>,
        //track_id: String,
        //stream_id: String,
    ) -> (Arc<WebRTCReceiver>, bool) {
        let track_id = track.id();
        let stream_id = track.stream_id();
        let mut published = false;
        let buffer = self.buffer_factory.get_or_new_buffer(track.ssrc());
        let sender = self.rtcp_sender_channel.clone();
        buffer
            .register_on_feedback(Box::new(
                move |packets: Vec<Box<dyn RtcpPacket + Send + Sync>>| {
                    let sender_in = Arc::clone(&sender);
                    Box::pin(async move {
                        if let Err(err) = sender_in.send(packets).await {
                            error!("send err: {}", err);
                        }
                    })
                },
            ))
            .await;

        match track.kind() {
            RTPCodecType::Audio => {
                let audio_observer = self.audio_observer.clone();
                let stream_id_out = stream_id.clone();
                buffer
                    .register_on_audio_level(Box::new(move |voice, level| {
                        let audio_observer_in = audio_observer.clone();
                        let stream_id = stream_id_out.clone();
                        Box::pin(async move {
                            if !voice {
                                debug!("[Stream {stream_id}] Skip invalid audio level.");
                                return;
                            }
                            audio_observer_in
                                .lock()
                                .await
                                .observe(&stream_id, level)
                                .await;
                        })
                    }))
                    .await;
                debug!(
                    "[Router {}] add stream {} to audio observer",
                    self.id, stream_id
                );
                self.audio_observer.lock().await.add_stream(stream_id).await;
            }
            RTPCodecType::Video => {
                // TODO: implement video rotation detection
            }
            _ => {}
        }

        // TODO: implement twcc
        // TODO: implement stats

        let rtcp_reader = self
            .buffer_factory
            .get_or_new_rtcp_buffer(track.ssrc());
        //let stats_out = Arc::clone(&self.stats);
        let buffer_out = Arc::clone(&buffer);
        let with_status = self.config.with_stats;
        let factory = self.buffer_factory.clone();
        rtcp_reader
            .set_on_packets(Box::new(move |pkts| {
                let buffer_in = Arc::clone(&buffer_out);
                let factory_in = factory.clone();
                Box::pin(async move {
                    for pkt in pkts {
                        match pkt.header().packet_type {
                            PacketType::SourceDescription => {
                                if let Some(_) = pkt.as_any().downcast_ref::<SourceDescription>() {
                                    
                                    // TODO: send stats
                                }
                                //info!("SourceDescription");
                            }
                            PacketType::SenderReport => {
                                if let Some(sender_report) =
                                pkt.as_any().downcast_ref::<SenderReport>()
                                {
                                    //info!("SenderReport");
                                    buffer_in
                                        .set_sender_report_data(
                                            sender_report.rtp_time,
                                            sender_report.ntp_time,
                                        )
                                        .await;
                                    if with_status {
                                        // TODO: update stats
                                    }
                                };
                            }
                            PacketType::Goodbye => {
                                if let Some(bye) = pkt.as_any().downcast_ref::<Goodbye>() {
                                    debug!("Bye packet");
                                    for ssrc in &bye.sources {
                                        match factory_in.get_rtp_buffer(*ssrc) {
                                            Some(buffer) => {
                                                // this function always returns Ok
                                                debug!("Closing buffer ssrc={ssrc}");
                                                buffer.close().await.unwrap();
                                            },
                                            _ => {
                                                warn!("Do not exist RTP buffer for closing track ssrc={ssrc}");
                                            }
                                        }
                                    }
                                }
                            }
                            packet_type => {
                                debug!("Unhandled packet type {}", packet_type);
                            }
                        }
                    }
                })
            }))
            .await;

        let arc_receiver;
        match self.receivers.get(&track_id) {
            Some(r) => arc_receiver = r.clone(),
            None => {
                let rtc_rv = self
                    .create_receiver(rtp_receiver.clone(), track.clone())
                    .await;
                arc_receiver = Arc::new(rtc_rv);
                self.receivers.insert(track_id, arc_receiver.clone());
                published = true;
                info!("Track {} published", track.id());
                
                if let Some(f) = &mut *self.on_add_receiver_track_handler.lock().await {
                    let _ = f(arc_receiver.clone()).await;
                }
            }
        }
        if let Some(layer) = arc_receiver
            .add_up_track(
                track.clone(),
                buffer.clone(),
                rtcp_reader.clone(),
                self.config.simulcast.best_quality_first,
            )
            .await
        {
            // Bind RTP
            buffer.bind(&rtp_receiver.get_parameters().await, PacketOptions {
                max_bitrate: self.config.max_bandwidth,
                rtx_enabled: self.config.with_rtx,
            }).await;
            
            layer.run_ingestion(rtp_receiver);
        }
        
        (arc_receiver, published)
    }

    async fn create_receiver(
        &self,
        rtp_receiver: Arc<RTCRtpReceiver>,
        track: Arc<TrackRemote>,
    ) -> WebRTCReceiver {
        let mut rv = WebRTCReceiver::new(rtp_receiver.clone(), track.clone(), self.id.clone());
        rv.set_rtcp_channel(self.rtcp_sender_channel.clone());
        let recv_kind = rv.kind();
        let stream_id = track.stream_id();
        let audio_observer = self.audio_observer.clone();
        rv.on_close(Box::new(move || {
            let stream_id_in = stream_id.clone();
            let observer_in = audio_observer.clone();
            Box::pin(async move {
                if recv_kind == RTPCodecType::Audio {
                    observer_in.lock().await.remove_stream(&stream_id_in).await;
                }
            })
        }))
        .await;
        rv
    }

    /// Starts a task that observes audio levels of the tracks in this router.
    ///
    /// Fires [RoomEvent::VoiceActivity] when audio activity from streams changes.
    ///
    /// Stops when `stop` signal is received.
    pub async fn start_audio_observer_task(&self) {
        let mut stop_receiver = self.stop_sender_channel.subscribe();
        let id_out = self.id.clone();
        let observer = self.audio_observer.clone();
        let interval_ms = observer.lock().await.interval as u64;
        let interval = Duration::from_millis(interval_ms);
        let room_out = self.room.clone();
        tokio::spawn(async move {
            loop {
                tokio::select! {
                    _ = sleep(interval) => {
                        let is_empty = {
                            observer.lock().await.is_empty().await
                        };

                        if is_empty {
                            continue;
                        }

                        let streams = {
                            observer.lock().await.calc().await
                        };

                        if let Some(streams) = streams {
                            if let Some(room) = room_out.upgrade() {
                                room.trigger_event(
                                    RoomEvent::VoiceActivity { room_id: room.id.clone(), stream_ids: streams }
                                );
                            } else {
                                warn!("Room should have reference in this task");
                            }
                        }
                    }
                    _ = stop_receiver.recv() => {
                        info!("[Router {}] Stopping audio observer task", id_out);
                        break;
                    }
                }
            }
        });
    }

    /// Sets the function to be called when an RTCP packet is received.
    pub async fn set_rtcp_writer(&self, writer: RtcpWriterFn) {
        let mut handler = self.rtcp_writer_handler.lock().await;
        *handler = Some(writer);
    }

    /// Forwards RTCP packets to the RTCP writer.
    pub async fn send_rtcp(&self) {
        let mut stop = self.stop_sender_channel.subscribe();
        let mut rtcp_receiver = self.rtcp_receiver_channel.lock().await;
        loop {
            //let mut rtcp_receiver = self.rtcp_receiver_channel.lock().await;
            tokio::select! {
              data = rtcp_receiver.recv() => {
                 if let Some(val) = data{
                    if let Some(f) = &mut *self.rtcp_writer_handler.lock().await {
                        let _ = f(val).await;
                    }
                }
              }
              _data = stop.recv() => {
                info!("Stop receiver signal. Exiting loop");
                return ;
              }
            };
        }
    }

    /// Sends `stop` signal in this router, and safely shuts down all associated receivers.
    /// This function is idempotent: it ensures that cleanup logic runs only once.
    /// Subsequent calls have no effect and return immediately.
    pub async fn stop(&self) {
        if self.closed.swap(true, Ordering::SeqCst) {
            trace!("[Router {}] stop, router already closed.", self.id);
            return;
        }

        info!("[Router {}] Stopping receivers", self.id);
        for item in self.receivers.iter() {
            let id = item.key();
            let receiver = item.value();

            info!("[Router {}] Closing receiver {}", self.id, id);
            receiver.close_tracks().await;
        }

        if let Err(err) = self.stop_sender_channel.send(()) {
            error!("stop err: {}", err);
        }
    }
}

impl Drop for LocalRouter {
    fn drop(&mut self) {
        if let Err(err) = self.stop_sender_channel.send(()) {
            error!("stop err: {}", err);
        }
    }
}
